name: Build PyTorch for Termux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout seu fork
        uses: actions/checkout@v4

      - name: Build PyTorch
        run: |
          # O builder precisa de algumas permissões de escrita
          sudo chmod -R 777 .

          # Executa o script de build que JÁ ESTÁ no seu repo
          # Ele vai usar o build.sh que está em packages/python-torch/
          ./start-builder.sh ./build-package.sh -a aarch64 python-torch

      - name: Upload do arquivo .deb
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-termux-package
          # O arquivo gerado vai para a pasta 'output'
          path: output/*.deb
